### ISSUE TITLE
Add ENVI Spectral Library import

### ISSUE THREAD

**Issue by robintw** [pmlrsg/PySpectra#1]

**Comment by robintw** [comment]
I'm sure I wrote code to do this, but I can't find it anywhere - so this will take a bit longer to implement.

**Comment by danclewley** [comment]
They are just ENVI format (binary with a header file). We have some code for reading ENVI files as NumPy arrays (without using GDAL) available from:
https://github.com/pmlrsg/arsf_tools/tree/master/arsf_envi_reader
So we should just be able to use a simplified version of this code.
Have re-assigned to myself.

**Comment by danclewley** [comment]
Added ENVI reader with https://github.com/pmlrsg/PySpectra/commit/e99163896058b0c7ca31ad1525d7b4f3d63a19c9. Once a test has been added this can be closed.

**Comment by danclewley** [comment]
Have now added a test. Marking as closed.
