### ISSUE TITLE
Convolution of spectra with SRFs?

### ISSUE THREAD

**Issue by robintw** [pmlrsg/PySpectra#8]
I've got a bit of code that takes a spectrum and convolves it with the Spectral Response Function of a sensor band, which I've used in a number of situations (eg. to compare field spectra with atmospherically-corrected Landsat images).

Do you think this would be useful to add to the library? I'm not sure if it's officially 'in scope' or not...

My plan would be to add a `convolve` method to the `Spectra` class. This would need to take an argument of the SRF - and I thought the easiest way to do this would be to represent the SRF as a `Spectra` object (with the `value_type` set to `"response"`). We could even add a library of SRFs for common sensors as well.

Any thoughts? I happened to find this code while searching for the code to read ENVI Spectral Library files (I _swear_ I wrote it, but I can't seem to find it!) and wondered about inclusion.

**Comment by danclewley** [comment]
Yes, I think this would be a great addition to the library. Your proposed implementation sounds good to me.
